name: Build Padavan E8820V2

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    env:
      images_dir: /opt/images
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y libtool-bin gperf python3-docutils autopoint gettext 7z

      - name: Prepare toolchain
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh

      - name: Start build
        run: |
          cd trunk
          mkdir -p ${images_dir}
          # Menjalankan build khusus target E8820V2
          fakeroot ./build_firmware_ci E8820V2
          if [ $? = 0 ]; then 
            cp -f images/*.trx ${images_dir}/E8820V2.trx
          else 
            exit 1
          fi

      - name: Upload images to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Padavan_ZTE_E8820V2
          path: /opt/images/E8820V2.trx
